stages:
  data_ingestion:
    cmd: python src/cnnClassifier/pipeline/stage_01_data_ingestion.py
    deps:
      - src/cnnClassifier/pipeline/stage_01_data_ingestion.py
      - config/config.yaml
    outs:
      - artifacts/data_ingestion/train_data
      - artifacts/data_ingestion/test_data


  prepare_base_model:
    cmd: python src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
    deps:
      - src/cnnClassifier/pipeline/stage_02_prepare_base_model.py
      - config/config.yaml
    params:
      - learning_rate
      - num_epochs
      - optimizer
      - batch_size
      - classes
    outs:
      - artifacts/prepare_base_model


  training_and_validation:
    cmd: python src/cnnClassifier/pipeline/stage_03_train_and_validation.py
    deps:
      - src/cnnClassifier/pipeline/stage_03_train_and_validation.py
      - config/config.yaml
      - artifacts/data_ingestion/train_data
      - artifacts/prepare_base_model
    params:
      - learning_rate
      - num_epochs
      - optimizer
      - batch_size
      - classes
    outs:
      - artifacts/training/model.pth


