artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data: artifacts/data_ingestion/train_data
  test_data: artifacts/data_ingestion/test_data

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.h5
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.h5