artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  train_data: artifacts/data_ingestion/train_data
  test_data: artifacts/data_ingestion/test_data

prepare_base_model:
  root_dir: artifacts/prepare_base_model
  base_model_path: artifacts/prepare_base_model/base_model.pth
  updated_base_model_path: artifacts/prepare_base_model/base_model_updated.pth

hyperparameters:
    root_dir: artifacts/best_hyperparameters

training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.h5